//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF_Swamp
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WCF_SWAMP")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Operacion", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public partial class Operacion : object
    {
        
        private string AgenciaField;
        
        private string BancaField;
        
        private string CICField;
        
        private WCF_Swamp.ServCanales CanalField;
        
        private string CentroField;
        
        private bool CerrarField;
        
        private string CodAgenciaField;
        
        private string ComplementoField;
        
        private string CorreoField;
        
        private string CuentaField;
        
        private string CuentaTramiteField;
        
        private string DescripcionTramiteField;
        
        private string DireccionField;
        
        private WCF_Swamp.Estado EstadoOperacionField;
        
        private string FacturaField;
        
        private string FuncionarioField;
        
        private string GlosaField;
        
        private string IDCField;
        
        private decimal ImporteField;
        
        private string MensageRespuestaField;
        
        private string MonedaField;
        
        private string NITField;
        
        private string NombreAgenciaField;
        
        private string NombreCompletoField;
        
        private string NroCasoField;
        
        private string NroOperacionField;
        
        private string OpSecuenciaField;
        
        private WCF_Swamp.CanalOrigen OrigenField;
        
        private long SecuenciaField;
        
        private WCF_Swamp.ServFacturacion ServFacturacionField;
        
        private string SucursalField;
        
        private string SupervisorField;
        
        private string TelefonoField;
        
        private WCF_Swamp.Accion TipAccionField;
        
        private WCF_Swamp.Facturacion TipoFacturacionField;
        
        private string UsuDominioField;
        
        private WCF_Swamp.Cobro cobroField;
        
        private WCF_Swamp.Devolucion devolucionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Agencia
        {
            get
            {
                return this.AgenciaField;
            }
            set
            {
                this.AgenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Banca
        {
            get
            {
                return this.BancaField;
            }
            set
            {
                this.BancaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CIC
        {
            get
            {
                return this.CICField;
            }
            set
            {
                this.CICField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.ServCanales Canal
        {
            get
            {
                return this.CanalField;
            }
            set
            {
                this.CanalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Centro
        {
            get
            {
                return this.CentroField;
            }
            set
            {
                this.CentroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Cerrar
        {
            get
            {
                return this.CerrarField;
            }
            set
            {
                this.CerrarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodAgencia
        {
            get
            {
                return this.CodAgenciaField;
            }
            set
            {
                this.CodAgenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Complemento
        {
            get
            {
                return this.ComplementoField;
            }
            set
            {
                this.ComplementoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuenta
        {
            get
            {
                return this.CuentaField;
            }
            set
            {
                this.CuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaTramite
        {
            get
            {
                return this.CuentaTramiteField;
            }
            set
            {
                this.CuentaTramiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionTramite
        {
            get
            {
                return this.DescripcionTramiteField;
            }
            set
            {
                this.DescripcionTramiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.Estado EstadoOperacion
        {
            get
            {
                return this.EstadoOperacionField;
            }
            set
            {
                this.EstadoOperacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Factura
        {
            get
            {
                return this.FacturaField;
            }
            set
            {
                this.FacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Funcionario
        {
            get
            {
                return this.FuncionarioField;
            }
            set
            {
                this.FuncionarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Glosa
        {
            get
            {
                return this.GlosaField;
            }
            set
            {
                this.GlosaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDC
        {
            get
            {
                return this.IDCField;
            }
            set
            {
                this.IDCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Importe
        {
            get
            {
                return this.ImporteField;
            }
            set
            {
                this.ImporteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensageRespuesta
        {
            get
            {
                return this.MensageRespuestaField;
            }
            set
            {
                this.MensageRespuestaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIT
        {
            get
            {
                return this.NITField;
            }
            set
            {
                this.NITField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreAgencia
        {
            get
            {
                return this.NombreAgenciaField;
            }
            set
            {
                this.NombreAgenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCompleto
        {
            get
            {
                return this.NombreCompletoField;
            }
            set
            {
                this.NombreCompletoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroCaso
        {
            get
            {
                return this.NroCasoField;
            }
            set
            {
                this.NroCasoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NroOperacion
        {
            get
            {
                return this.NroOperacionField;
            }
            set
            {
                this.NroOperacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OpSecuencia
        {
            get
            {
                return this.OpSecuenciaField;
            }
            set
            {
                this.OpSecuenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.CanalOrigen Origen
        {
            get
            {
                return this.OrigenField;
            }
            set
            {
                this.OrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Secuencia
        {
            get
            {
                return this.SecuenciaField;
            }
            set
            {
                this.SecuenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.ServFacturacion ServFacturacion
        {
            get
            {
                return this.ServFacturacionField;
            }
            set
            {
                this.ServFacturacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Sucursal
        {
            get
            {
                return this.SucursalField;
            }
            set
            {
                this.SucursalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Supervisor
        {
            get
            {
                return this.SupervisorField;
            }
            set
            {
                this.SupervisorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.Accion TipAccion
        {
            get
            {
                return this.TipAccionField;
            }
            set
            {
                this.TipAccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.Facturacion TipoFacturacion
        {
            get
            {
                return this.TipoFacturacionField;
            }
            set
            {
                this.TipoFacturacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UsuDominio
        {
            get
            {
                return this.UsuDominioField;
            }
            set
            {
                this.UsuDominioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.Cobro cobro
        {
            get
            {
                return this.cobroField;
            }
            set
            {
                this.cobroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.Devolucion devolucion
        {
            get
            {
                return this.devolucionField;
            }
            set
            {
                this.devolucionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServCanales", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public partial class ServCanales : object
    {
        
        private string CuentaField;
        
        private int IdField;
        
        private string ProductoField;
        
        private string claveField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuenta
        {
            get
            {
                return this.CuentaField;
            }
            set
            {
                this.CuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Producto
        {
            get
            {
                return this.ProductoField;
            }
            set
            {
                this.ProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServFacturacion", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public partial class ServFacturacion : object
    {
        
        private string DescripcionField;
        
        private int IdField;
        
        private string claveField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string clave
        {
            get
            {
                return this.claveField;
            }
            set
            {
                this.claveField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cobro", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public partial class Cobro : object
    {
        
        private int CIERRA_SWAMPField;
        
        private int COBRO_PLATAFORMAField;
        
        private int COBRO_PRField;
        
        private string DESCRIPCIONField;
        
        private string DESC_PRODField;
        
        private string DESC_SERVField;
        
        private int FACTURABLEField;
        
        private string GLOSAField;
        
        private int HABILITADOField;
        
        private int ID_COBROField;
        
        private int PERIODOField;
        
        private string PRODUCTO_PRField;
        
        private int SERV_CANALESField;
        
        private int SERV_FACTURACIONField;
        
        private string SERV_PRField;
        
        private int TARIFARIOField;
        
        private int VIA_ENVIOField;
        
        private int VISIBLE_PRField;
        
        private int VISIBLE_SWAMPField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CIERRA_SWAMP
        {
            get
            {
                return this.CIERRA_SWAMPField;
            }
            set
            {
                this.CIERRA_SWAMPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COBRO_PLATAFORMA
        {
            get
            {
                return this.COBRO_PLATAFORMAField;
            }
            set
            {
                this.COBRO_PLATAFORMAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int COBRO_PR
        {
            get
            {
                return this.COBRO_PRField;
            }
            set
            {
                this.COBRO_PRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION
        {
            get
            {
                return this.DESCRIPCIONField;
            }
            set
            {
                this.DESCRIPCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESC_PROD
        {
            get
            {
                return this.DESC_PRODField;
            }
            set
            {
                this.DESC_PRODField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESC_SERV
        {
            get
            {
                return this.DESC_SERVField;
            }
            set
            {
                this.DESC_SERVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int FACTURABLE
        {
            get
            {
                return this.FACTURABLEField;
            }
            set
            {
                this.FACTURABLEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GLOSA
        {
            get
            {
                return this.GLOSAField;
            }
            set
            {
                this.GLOSAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HABILITADO
        {
            get
            {
                return this.HABILITADOField;
            }
            set
            {
                this.HABILITADOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_COBRO
        {
            get
            {
                return this.ID_COBROField;
            }
            set
            {
                this.ID_COBROField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int PERIODO
        {
            get
            {
                return this.PERIODOField;
            }
            set
            {
                this.PERIODOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODUCTO_PR
        {
            get
            {
                return this.PRODUCTO_PRField;
            }
            set
            {
                this.PRODUCTO_PRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SERV_CANALES
        {
            get
            {
                return this.SERV_CANALESField;
            }
            set
            {
                this.SERV_CANALESField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SERV_FACTURACION
        {
            get
            {
                return this.SERV_FACTURACIONField;
            }
            set
            {
                this.SERV_FACTURACIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SERV_PR
        {
            get
            {
                return this.SERV_PRField;
            }
            set
            {
                this.SERV_PRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TARIFARIO
        {
            get
            {
                return this.TARIFARIOField;
            }
            set
            {
                this.TARIFARIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VIA_ENVIO
        {
            get
            {
                return this.VIA_ENVIOField;
            }
            set
            {
                this.VIA_ENVIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VISIBLE_PR
        {
            get
            {
                return this.VISIBLE_PRField;
            }
            set
            {
                this.VISIBLE_PRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VISIBLE_SWAMP
        {
            get
            {
                return this.VISIBLE_SWAMPField;
            }
            set
            {
                this.VISIBLE_SWAMPField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Devolucion", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public partial class Devolucion : object
    {
        
        private string DESCRIPCIONField;
        
        private string DESC_PRODField;
        
        private string DESC_SERVField;
        
        private string FUNCIONARIOField;
        
        private string GLOSAField;
        
        private int HABILITADOField;
        
        private int ID_DEVOLUCIONField;
        
        private string PRODUCTO_PRField;
        
        private string SERVICIO_PRField;
        
        private int SERV_CANALESField;
        
        private int TARIFARIOField;
        
        private int VISIBLE_PRField;
        
        private int VISIBLE_SWAMPField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESCRIPCION
        {
            get
            {
                return this.DESCRIPCIONField;
            }
            set
            {
                this.DESCRIPCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESC_PROD
        {
            get
            {
                return this.DESC_PRODField;
            }
            set
            {
                this.DESC_PRODField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DESC_SERV
        {
            get
            {
                return this.DESC_SERVField;
            }
            set
            {
                this.DESC_SERVField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FUNCIONARIO
        {
            get
            {
                return this.FUNCIONARIOField;
            }
            set
            {
                this.FUNCIONARIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GLOSA
        {
            get
            {
                return this.GLOSAField;
            }
            set
            {
                this.GLOSAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HABILITADO
        {
            get
            {
                return this.HABILITADOField;
            }
            set
            {
                this.HABILITADOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ID_DEVOLUCION
        {
            get
            {
                return this.ID_DEVOLUCIONField;
            }
            set
            {
                this.ID_DEVOLUCIONField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PRODUCTO_PR
        {
            get
            {
                return this.PRODUCTO_PRField;
            }
            set
            {
                this.PRODUCTO_PRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SERVICIO_PR
        {
            get
            {
                return this.SERVICIO_PRField;
            }
            set
            {
                this.SERVICIO_PRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SERV_CANALES
        {
            get
            {
                return this.SERV_CANALESField;
            }
            set
            {
                this.SERV_CANALESField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TARIFARIO
        {
            get
            {
                return this.TARIFARIOField;
            }
            set
            {
                this.TARIFARIOField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VISIBLE_PR
        {
            get
            {
                return this.VISIBLE_PRField;
            }
            set
            {
                this.VISIBLE_PRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int VISIBLE_SWAMP
        {
            get
            {
                return this.VISIBLE_SWAMPField;
            }
            set
            {
                this.VISIBLE_SWAMPField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Estado", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public enum Estado : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No_Definido = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Realizado = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        No_Realizado = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CanalOrigen", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public enum CanalOrigen : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SWAMP = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        PR = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Accion", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public enum Accion : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cobro = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Devolucion = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Facturacion", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public enum Facturacion : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Online_SIN = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Online_Transactor = 1,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public partial class Respuesta : object
    {
        
        private bool ErrorField;
        
        private WCF_Swamp.FacturacionResp FacturaField;
        
        private string MensajeClienteField;
        
        private string MensajeErrorField;
        
        private string cufField;
        
        private WCF_Swamp.Operacion[] operacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Error
        {
            get
            {
                return this.ErrorField;
            }
            set
            {
                this.ErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.FacturacionResp Factura
        {
            get
            {
                return this.FacturaField;
            }
            set
            {
                this.FacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeCliente
        {
            get
            {
                return this.MensajeClienteField;
            }
            set
            {
                this.MensajeClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MensajeError
        {
            get
            {
                return this.MensajeErrorField;
            }
            set
            {
                this.MensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cuf
        {
            get
            {
                return this.cufField;
            }
            set
            {
                this.cufField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.Operacion[] operacion
        {
            get
            {
                return this.operacionField;
            }
            set
            {
                this.operacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturacionResp", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public partial class FacturacionResp : object
    {
        
        private string AutorizacionField;
        
        private string CantidadField;
        
        private string CodControlField;
        
        private string CodRespField;
        
        private byte[] CodigoQRField;
        
        private string DescripcionDetalleField;
        
        private string DireccionField;
        
        private string FacturaField;
        
        private string LiteralField;
        
        private string MensajeField;
        
        private string NITField;
        
        private string RazonField;
        
        private string TotalField;
        
        private string VencimientoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autorizacion
        {
            get
            {
                return this.AutorizacionField;
            }
            set
            {
                this.AutorizacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodControl
        {
            get
            {
                return this.CodControlField;
            }
            set
            {
                this.CodControlField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodResp
        {
            get
            {
                return this.CodRespField;
            }
            set
            {
                this.CodRespField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte[] CodigoQR
        {
            get
            {
                return this.CodigoQRField;
            }
            set
            {
                this.CodigoQRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionDetalle
        {
            get
            {
                return this.DescripcionDetalleField;
            }
            set
            {
                this.DescripcionDetalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Direccion
        {
            get
            {
                return this.DireccionField;
            }
            set
            {
                this.DireccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Factura
        {
            get
            {
                return this.FacturaField;
            }
            set
            {
                this.FacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Literal
        {
            get
            {
                return this.LiteralField;
            }
            set
            {
                this.LiteralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensaje
        {
            get
            {
                return this.MensajeField;
            }
            set
            {
                this.MensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIT
        {
            get
            {
                return this.NITField;
            }
            set
            {
                this.NITField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Razon
        {
            get
            {
                return this.RazonField;
            }
            set
            {
                this.RazonField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Total
        {
            get
            {
                return this.TotalField;
            }
            set
            {
                this.TotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Vencimiento
        {
            get
            {
                return this.VencimientoField;
            }
            set
            {
                this.VencimientoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CobroSwamp2019Response", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public partial class CobroSwamp2019Response : object
    {
        
        private string cufField;
        
        private string detalleField;
        
        private bool exitoField;
        
        private string mensajeClienteField;
        
        private string mensajeErrorField;
        
        private WCF_Swamp.Operacion[] operacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cuf
        {
            get
            {
                return this.cufField;
            }
            set
            {
                this.cufField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string detalle
        {
            get
            {
                return this.detalleField;
            }
            set
            {
                this.detalleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool exito
        {
            get
            {
                return this.exitoField;
            }
            set
            {
                this.exitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensajeCliente
        {
            get
            {
                return this.mensajeClienteField;
            }
            set
            {
                this.mensajeClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensajeError
        {
            get
            {
                return this.mensajeErrorField;
            }
            set
            {
                this.mensajeErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.Operacion[] operacion
        {
            get
            {
                return this.operacionField;
            }
            set
            {
                this.operacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaFactura2019Request", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public partial class ConsultaFactura2019Request : object
    {
        
        private string aplicacionField;
        
        private string cufField;
        
        private int formatoFacturaField;
        
        private string idcComplementoField;
        
        private string idcExtensionField;
        
        private string idcNumeroField;
        
        private string idcTipoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string aplicacion
        {
            get
            {
                return this.aplicacionField;
            }
            set
            {
                this.aplicacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cuf
        {
            get
            {
                return this.cufField;
            }
            set
            {
                this.cufField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int formatoFactura
        {
            get
            {
                return this.formatoFacturaField;
            }
            set
            {
                this.formatoFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idcComplemento
        {
            get
            {
                return this.idcComplementoField;
            }
            set
            {
                this.idcComplementoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idcExtension
        {
            get
            {
                return this.idcExtensionField;
            }
            set
            {
                this.idcExtensionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idcNumero
        {
            get
            {
                return this.idcNumeroField;
            }
            set
            {
                this.idcNumeroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string idcTipo
        {
            get
            {
                return this.idcTipoField;
            }
            set
            {
                this.idcTipoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsultaFactura2019Response", Namespace="http://schemas.datacontract.org/2004/07/Entidades")]
    public partial class ConsultaFactura2019Response : object
    {
        
        private string errorField;
        
        private bool exitoField;
        
        private WCF_Swamp.FacturaItem facturaField;
        
        private string mensajeField;
        
        private string pdfField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string error
        {
            get
            {
                return this.errorField;
            }
            set
            {
                this.errorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool exito
        {
            get
            {
                return this.exitoField;
            }
            set
            {
                this.exitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.FacturaItem factura
        {
            get
            {
                return this.facturaField;
            }
            set
            {
                this.facturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mensaje
        {
            get
            {
                return this.mensajeField;
            }
            set
            {
                this.mensajeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string pdf
        {
            get
            {
                return this.pdfField;
            }
            set
            {
                this.pdfField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FacturaItem", Namespace="http://schemas.datacontract.org/2004/07/BCP.Facturacion.Entidades")]
    public partial class FacturaItem : object
    {
        
        private string CICField;
        
        private string CUFField;
        
        private string CUFDField;
        
        private WCF_Swamp.CabeceraItem CabeceraField;
        
        private int CodigoMetodoPagoField;
        
        private string ComplementoIDCField;
        
        private string CuentaField;
        
        private WCF_Swamp.DetalleFacturaItem[] DetalleFacturaField;
        
        private string FechaHoraField;
        
        private string FechaLimiteEmisionField;
        
        private string IDCField;
        
        private string LeyendaField;
        
        private string MonedaField;
        
        private decimal MontoDescuentoField;
        
        private string MontoLiteralField;
        
        private decimal MontoTotalArrendamientoFinancieroField;
        
        private decimal MontoTotalFacturadoField;
        
        private decimal MontoTotalMonedaField;
        
        private string NITField;
        
        private string QRField;
        
        private string RazonSocialField;
        
        private string TipoCambioField;
        
        private string TipoIDCField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CIC
        {
            get
            {
                return this.CICField;
            }
            set
            {
                this.CICField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUF
        {
            get
            {
                return this.CUFField;
            }
            set
            {
                this.CUFField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CUFD
        {
            get
            {
                return this.CUFDField;
            }
            set
            {
                this.CUFDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.CabeceraItem Cabecera
        {
            get
            {
                return this.CabeceraField;
            }
            set
            {
                this.CabeceraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoMetodoPago
        {
            get
            {
                return this.CodigoMetodoPagoField;
            }
            set
            {
                this.CodigoMetodoPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComplementoIDC
        {
            get
            {
                return this.ComplementoIDCField;
            }
            set
            {
                this.ComplementoIDCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cuenta
        {
            get
            {
                return this.CuentaField;
            }
            set
            {
                this.CuentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public WCF_Swamp.DetalleFacturaItem[] DetalleFactura
        {
            get
            {
                return this.DetalleFacturaField;
            }
            set
            {
                this.DetalleFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaHora
        {
            get
            {
                return this.FechaHoraField;
            }
            set
            {
                this.FechaHoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FechaLimiteEmision
        {
            get
            {
                return this.FechaLimiteEmisionField;
            }
            set
            {
                this.FechaLimiteEmisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IDC
        {
            get
            {
                return this.IDCField;
            }
            set
            {
                this.IDCField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Leyenda
        {
            get
            {
                return this.LeyendaField;
            }
            set
            {
                this.LeyendaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoDescuento
        {
            get
            {
                return this.MontoDescuentoField;
            }
            set
            {
                this.MontoDescuentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MontoLiteral
        {
            get
            {
                return this.MontoLiteralField;
            }
            set
            {
                this.MontoLiteralField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoTotalArrendamientoFinanciero
        {
            get
            {
                return this.MontoTotalArrendamientoFinancieroField;
            }
            set
            {
                this.MontoTotalArrendamientoFinancieroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoTotalFacturado
        {
            get
            {
                return this.MontoTotalFacturadoField;
            }
            set
            {
                this.MontoTotalFacturadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoTotalMoneda
        {
            get
            {
                return this.MontoTotalMonedaField;
            }
            set
            {
                this.MontoTotalMonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NIT
        {
            get
            {
                return this.NITField;
            }
            set
            {
                this.NITField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string QR
        {
            get
            {
                return this.QRField;
            }
            set
            {
                this.QRField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial
        {
            get
            {
                return this.RazonSocialField;
            }
            set
            {
                this.RazonSocialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoCambio
        {
            get
            {
                return this.TipoCambioField;
            }
            set
            {
                this.TipoCambioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoIDC
        {
            get
            {
                return this.TipoIDCField;
            }
            set
            {
                this.TipoIDCField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CabeceraItem", Namespace="http://schemas.datacontract.org/2004/07/BCP.Facturacion.Entidades")]
    public partial class CabeceraItem : object
    {
        
        private string ActividadEconomicaField;
        
        private int CodigoTipoDocumentoSectorField;
        
        private string DepartamentoField;
        
        private string DescripcionSucursalField;
        
        private string DireccionDomicilioField;
        
        private string MunicipioField;
        
        private string NITEmisorField;
        
        private string NumeroFacturaField;
        
        private string RazonSocialEmisorField;
        
        private string SucursalBCPField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActividadEconomica
        {
            get
            {
                return this.ActividadEconomicaField;
            }
            set
            {
                this.ActividadEconomicaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoTipoDocumentoSector
        {
            get
            {
                return this.CodigoTipoDocumentoSectorField;
            }
            set
            {
                this.CodigoTipoDocumentoSectorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Departamento
        {
            get
            {
                return this.DepartamentoField;
            }
            set
            {
                this.DepartamentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionSucursal
        {
            get
            {
                return this.DescripcionSucursalField;
            }
            set
            {
                this.DescripcionSucursalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DireccionDomicilio
        {
            get
            {
                return this.DireccionDomicilioField;
            }
            set
            {
                this.DireccionDomicilioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Municipio
        {
            get
            {
                return this.MunicipioField;
            }
            set
            {
                this.MunicipioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NITEmisor
        {
            get
            {
                return this.NITEmisorField;
            }
            set
            {
                this.NITEmisorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroFactura
        {
            get
            {
                return this.NumeroFacturaField;
            }
            set
            {
                this.NumeroFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocialEmisor
        {
            get
            {
                return this.RazonSocialEmisorField;
            }
            set
            {
                this.RazonSocialEmisorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SucursalBCP
        {
            get
            {
                return this.SucursalBCPField;
            }
            set
            {
                this.SucursalBCPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DetalleFacturaItem", Namespace="http://schemas.datacontract.org/2004/07/BCP.Facturacion.Entidades")]
    public partial class DetalleFacturaItem : object
    {
        
        private int CantidadServicioField;
        
        private string CodigoProductoField;
        
        private string DescripcionField;
        
        private decimal MontoOriginalField;
        
        private decimal PrecioUnitarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CantidadServicio
        {
            get
            {
                return this.CantidadServicioField;
            }
            set
            {
                this.CantidadServicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoProducto
        {
            get
            {
                return this.CodigoProductoField;
            }
            set
            {
                this.CodigoProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoOriginal
        {
            get
            {
                return this.MontoOriginalField;
            }
            set
            {
                this.MontoOriginalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal PrecioUnitario
        {
            get
            {
                return this.PrecioUnitarioField;
            }
            set
            {
                this.PrecioUnitarioField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF_Swamp.IService1")]
    public interface IService1
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<WCF_Swamp.CompositeType> GetDataUsingDataContractAsync(WCF_Swamp.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CobroSWAMP", ReplyAction="http://tempuri.org/IService1/CobroSWAMPResponse")]
        System.Threading.Tasks.Task<WCF_Swamp.Respuesta> CobroSWAMPAsync(WCF_Swamp.Operacion[] Operaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AbonosSWAMP", ReplyAction="http://tempuri.org/IService1/AbonosSWAMPResponse")]
        System.Threading.Tasks.Task<WCF_Swamp.Respuesta> AbonosSWAMPAsync(WCF_Swamp.Operacion[] Operaciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ValidacionGremio", ReplyAction="http://tempuri.org/IService1/ValidacionGremioResponse")]
        System.Threading.Tasks.Task<string> ValidacionGremioAsync(string IDC);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CobroSWAMP2019", ReplyAction="http://tempuri.org/IService1/CobroSWAMP2019Response")]
        System.Threading.Tasks.Task<WCF_Swamp.CobroSwamp2019Response> CobroSWAMP2019Async(WCF_Swamp.Operacion[] Operaciones, string aplicacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ConsultaFactura2019", ReplyAction="http://tempuri.org/IService1/ConsultaFactura2019Response")]
        System.Threading.Tasks.Task<WCF_Swamp.ConsultaFactura2019Response> ConsultaFactura2019Async(WCF_Swamp.ConsultaFactura2019Request request);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface IService1Channel : WCF_Swamp.IService1, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class Service1Client : System.ServiceModel.ClientBase<WCF_Swamp.IService1>, WCF_Swamp.IService1
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Service1Client() : 
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }
        
        public System.Threading.Tasks.Task<WCF_Swamp.CompositeType> GetDataUsingDataContractAsync(WCF_Swamp.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Threading.Tasks.Task<WCF_Swamp.Respuesta> CobroSWAMPAsync(WCF_Swamp.Operacion[] Operaciones)
        {
            return base.Channel.CobroSWAMPAsync(Operaciones);
        }
        
        public System.Threading.Tasks.Task<WCF_Swamp.Respuesta> AbonosSWAMPAsync(WCF_Swamp.Operacion[] Operaciones)
        {
            return base.Channel.AbonosSWAMPAsync(Operaciones);
        }
        
        public System.Threading.Tasks.Task<string> ValidacionGremioAsync(string IDC)
        {
            return base.Channel.ValidacionGremioAsync(IDC);
        }
        
        public System.Threading.Tasks.Task<WCF_Swamp.CobroSwamp2019Response> CobroSWAMP2019Async(WCF_Swamp.Operacion[] Operaciones, string aplicacion)
        {
            return base.Channel.CobroSWAMP2019Async(Operaciones, aplicacion);
        }
        
        public System.Threading.Tasks.Task<WCF_Swamp.ConsultaFactura2019Response> ConsultaFactura2019Async(WCF_Swamp.ConsultaFactura2019Request request)
        {
            return base.Channel.ConsultaFactura2019Async(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://devben00.bancred.com.bo/WCF_SWAMPV2/Service1.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IService1,
        }
    }
}
