//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace srvSharepointDws
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", ConfigurationName="srvSharepointDws.DwsSoap")]
    public interface DwsSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/dws/CreateDws", ReplyAction="*")]
        System.Threading.Tasks.Task<srvSharepointDws.CreateDwsResponse> CreateDwsAsync(srvSharepointDws.CreateDwsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/dws/DeleteDws", ReplyAction="*")]
        System.Threading.Tasks.Task<srvSharepointDws.DeleteDwsResponse> DeleteDwsAsync(srvSharepointDws.DeleteDwsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/dws/GetDwsMetaData", ReplyAction="*")]
        System.Threading.Tasks.Task<srvSharepointDws.GetDwsMetaDataResponse> GetDwsMetaDataAsync(srvSharepointDws.GetDwsMetaDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/dws/GetDwsData", ReplyAction="*")]
        System.Threading.Tasks.Task<srvSharepointDws.GetDwsDataResponse> GetDwsDataAsync(srvSharepointDws.GetDwsDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/dws/UpdateDwsData", ReplyAction="*")]
        System.Threading.Tasks.Task<srvSharepointDws.UpdateDwsDataResponse> UpdateDwsDataAsync(srvSharepointDws.UpdateDwsDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/dws/RemoveDwsUser", ReplyAction="*")]
        System.Threading.Tasks.Task<srvSharepointDws.RemoveDwsUserResponse> RemoveDwsUserAsync(srvSharepointDws.RemoveDwsUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/dws/RenameDws", ReplyAction="*")]
        System.Threading.Tasks.Task<srvSharepointDws.RenameDwsResponse> RenameDwsAsync(srvSharepointDws.RenameDwsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/dws/FindDwsDoc", ReplyAction="*")]
        System.Threading.Tasks.Task<srvSharepointDws.FindDwsDocResponse> FindDwsDocAsync(srvSharepointDws.FindDwsDocRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/dws/CanCreateDwsUrl", ReplyAction="*")]
        System.Threading.Tasks.Task<srvSharepointDws.CanCreateDwsUrlResponse> CanCreateDwsUrlAsync(srvSharepointDws.CanCreateDwsUrlRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/dws/CreateFolder", ReplyAction="*")]
        System.Threading.Tasks.Task<srvSharepointDws.CreateFolderResponse> CreateFolderAsync(srvSharepointDws.CreateFolderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://schemas.microsoft.com/sharepoint/soap/dws/DeleteFolder", ReplyAction="*")]
        System.Threading.Tasks.Task<srvSharepointDws.DeleteFolderResponse> DeleteFolderAsync(srvSharepointDws.DeleteFolderRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDwsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDws", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.CreateDwsRequestBody Body;
        
        public CreateDwsRequest()
        {
        }
        
        public CreateDwsRequest(srvSharepointDws.CreateDwsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class CreateDwsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string users;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string title;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string documents;
        
        public CreateDwsRequestBody()
        {
        }
        
        public CreateDwsRequestBody(string name, string users, string title, string documents)
        {
            this.name = name;
            this.users = users;
            this.title = title;
            this.documents = documents;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDwsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDwsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.CreateDwsResponseBody Body;
        
        public CreateDwsResponse()
        {
        }
        
        public CreateDwsResponse(srvSharepointDws.CreateDwsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class CreateDwsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateDwsResult;
        
        public CreateDwsResponseBody()
        {
        }
        
        public CreateDwsResponseBody(string CreateDwsResult)
        {
            this.CreateDwsResult = CreateDwsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDwsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDws", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.DeleteDwsRequestBody Body;
        
        public DeleteDwsRequest()
        {
        }
        
        public DeleteDwsRequest(srvSharepointDws.DeleteDwsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class DeleteDwsRequestBody
    {
        
        public DeleteDwsRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteDwsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteDwsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.DeleteDwsResponseBody Body;
        
        public DeleteDwsResponse()
        {
        }
        
        public DeleteDwsResponse(srvSharepointDws.DeleteDwsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class DeleteDwsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteDwsResult;
        
        public DeleteDwsResponseBody()
        {
        }
        
        public DeleteDwsResponseBody(string DeleteDwsResult)
        {
            this.DeleteDwsResult = DeleteDwsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDwsMetaDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDwsMetaData", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.GetDwsMetaDataRequestBody Body;
        
        public GetDwsMetaDataRequest()
        {
        }
        
        public GetDwsMetaDataRequest(srvSharepointDws.GetDwsMetaDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class GetDwsMetaDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string document;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string id;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public bool minimal;
        
        public GetDwsMetaDataRequestBody()
        {
        }
        
        public GetDwsMetaDataRequestBody(string document, string id, bool minimal)
        {
            this.document = document;
            this.id = id;
            this.minimal = minimal;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDwsMetaDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDwsMetaDataResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.GetDwsMetaDataResponseBody Body;
        
        public GetDwsMetaDataResponse()
        {
        }
        
        public GetDwsMetaDataResponse(srvSharepointDws.GetDwsMetaDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class GetDwsMetaDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDwsMetaDataResult;
        
        public GetDwsMetaDataResponseBody()
        {
        }
        
        public GetDwsMetaDataResponseBody(string GetDwsMetaDataResult)
        {
            this.GetDwsMetaDataResult = GetDwsMetaDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDwsDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDwsData", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.GetDwsDataRequestBody Body;
        
        public GetDwsDataRequest()
        {
        }
        
        public GetDwsDataRequest(srvSharepointDws.GetDwsDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class GetDwsDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string document;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string lastUpdate;
        
        public GetDwsDataRequestBody()
        {
        }
        
        public GetDwsDataRequestBody(string document, string lastUpdate)
        {
            this.document = document;
            this.lastUpdate = lastUpdate;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDwsDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDwsDataResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.GetDwsDataResponseBody Body;
        
        public GetDwsDataResponse()
        {
        }
        
        public GetDwsDataResponse(srvSharepointDws.GetDwsDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class GetDwsDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GetDwsDataResult;
        
        public GetDwsDataResponseBody()
        {
        }
        
        public GetDwsDataResponseBody(string GetDwsDataResult)
        {
            this.GetDwsDataResult = GetDwsDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDwsDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDwsData", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.UpdateDwsDataRequestBody Body;
        
        public UpdateDwsDataRequest()
        {
        }
        
        public UpdateDwsDataRequest(srvSharepointDws.UpdateDwsDataRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class UpdateDwsDataRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string updates;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string meetingInstance;
        
        public UpdateDwsDataRequestBody()
        {
        }
        
        public UpdateDwsDataRequestBody(string updates, string meetingInstance)
        {
            this.updates = updates;
            this.meetingInstance = meetingInstance;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDwsDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDwsDataResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.UpdateDwsDataResponseBody Body;
        
        public UpdateDwsDataResponse()
        {
        }
        
        public UpdateDwsDataResponse(srvSharepointDws.UpdateDwsDataResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class UpdateDwsDataResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateDwsDataResult;
        
        public UpdateDwsDataResponseBody()
        {
        }
        
        public UpdateDwsDataResponseBody(string UpdateDwsDataResult)
        {
            this.UpdateDwsDataResult = UpdateDwsDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveDwsUserRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveDwsUser", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.RemoveDwsUserRequestBody Body;
        
        public RemoveDwsUserRequest()
        {
        }
        
        public RemoveDwsUserRequest(srvSharepointDws.RemoveDwsUserRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class RemoveDwsUserRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public RemoveDwsUserRequestBody()
        {
        }
        
        public RemoveDwsUserRequestBody(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RemoveDwsUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RemoveDwsUserResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.RemoveDwsUserResponseBody Body;
        
        public RemoveDwsUserResponse()
        {
        }
        
        public RemoveDwsUserResponse(srvSharepointDws.RemoveDwsUserResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class RemoveDwsUserResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RemoveDwsUserResult;
        
        public RemoveDwsUserResponseBody()
        {
        }
        
        public RemoveDwsUserResponseBody(string RemoveDwsUserResult)
        {
            this.RemoveDwsUserResult = RemoveDwsUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RenameDwsRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RenameDws", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.RenameDwsRequestBody Body;
        
        public RenameDwsRequest()
        {
        }
        
        public RenameDwsRequest(srvSharepointDws.RenameDwsRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class RenameDwsRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string title;
        
        public RenameDwsRequestBody()
        {
        }
        
        public RenameDwsRequestBody(string title)
        {
            this.title = title;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class RenameDwsResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="RenameDwsResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.RenameDwsResponseBody Body;
        
        public RenameDwsResponse()
        {
        }
        
        public RenameDwsResponse(srvSharepointDws.RenameDwsResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class RenameDwsResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string RenameDwsResult;
        
        public RenameDwsResponseBody()
        {
        }
        
        public RenameDwsResponseBody(string RenameDwsResult)
        {
            this.RenameDwsResult = RenameDwsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindDwsDocRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindDwsDoc", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.FindDwsDocRequestBody Body;
        
        public FindDwsDocRequest()
        {
        }
        
        public FindDwsDocRequest(srvSharepointDws.FindDwsDocRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class FindDwsDocRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string id;
        
        public FindDwsDocRequestBody()
        {
        }
        
        public FindDwsDocRequestBody(string id)
        {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FindDwsDocResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FindDwsDocResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.FindDwsDocResponseBody Body;
        
        public FindDwsDocResponse()
        {
        }
        
        public FindDwsDocResponse(srvSharepointDws.FindDwsDocResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class FindDwsDocResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string FindDwsDocResult;
        
        public FindDwsDocResponseBody()
        {
        }
        
        public FindDwsDocResponseBody(string FindDwsDocResult)
        {
            this.FindDwsDocResult = FindDwsDocResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CanCreateDwsUrlRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CanCreateDwsUrl", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.CanCreateDwsUrlRequestBody Body;
        
        public CanCreateDwsUrlRequest()
        {
        }
        
        public CanCreateDwsUrlRequest(srvSharepointDws.CanCreateDwsUrlRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class CanCreateDwsUrlRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        public CanCreateDwsUrlRequestBody()
        {
        }
        
        public CanCreateDwsUrlRequestBody(string url)
        {
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CanCreateDwsUrlResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CanCreateDwsUrlResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.CanCreateDwsUrlResponseBody Body;
        
        public CanCreateDwsUrlResponse()
        {
        }
        
        public CanCreateDwsUrlResponse(srvSharepointDws.CanCreateDwsUrlResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class CanCreateDwsUrlResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CanCreateDwsUrlResult;
        
        public CanCreateDwsUrlResponseBody()
        {
        }
        
        public CanCreateDwsUrlResponseBody(string CanCreateDwsUrlResult)
        {
            this.CanCreateDwsUrlResult = CanCreateDwsUrlResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFolderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFolder", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.CreateFolderRequestBody Body;
        
        public CreateFolderRequest()
        {
        }
        
        public CreateFolderRequest(srvSharepointDws.CreateFolderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class CreateFolderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        public CreateFolderRequestBody()
        {
        }
        
        public CreateFolderRequestBody(string url)
        {
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFolderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFolderResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.CreateFolderResponseBody Body;
        
        public CreateFolderResponse()
        {
        }
        
        public CreateFolderResponse(srvSharepointDws.CreateFolderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class CreateFolderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateFolderResult;
        
        public CreateFolderResponseBody()
        {
        }
        
        public CreateFolderResponseBody(string CreateFolderResult)
        {
            this.CreateFolderResult = CreateFolderResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFolderRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFolder", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.DeleteFolderRequestBody Body;
        
        public DeleteFolderRequest()
        {
        }
        
        public DeleteFolderRequest(srvSharepointDws.DeleteFolderRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class DeleteFolderRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string url;
        
        public DeleteFolderRequestBody()
        {
        }
        
        public DeleteFolderRequestBody(string url)
        {
            this.url = url;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFolderResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFolderResponse", Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/", Order=0)]
        public srvSharepointDws.DeleteFolderResponseBody Body;
        
        public DeleteFolderResponse()
        {
        }
        
        public DeleteFolderResponse(srvSharepointDws.DeleteFolderResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/sharepoint/soap/dws/")]
    public partial class DeleteFolderResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteFolderResult;
        
        public DeleteFolderResponseBody()
        {
        }
        
        public DeleteFolderResponseBody(string DeleteFolderResult)
        {
            this.DeleteFolderResult = DeleteFolderResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public interface DwsSoapChannel : srvSharepointDws.DwsSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3")]
    public partial class DwsSoapClient : System.ServiceModel.ClientBase<srvSharepointDws.DwsSoap>, srvSharepointDws.DwsSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public DwsSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(DwsSoapClient.GetBindingForEndpoint(endpointConfiguration), DwsSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DwsSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(DwsSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DwsSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(DwsSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public DwsSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srvSharepointDws.CreateDwsResponse> srvSharepointDws.DwsSoap.CreateDwsAsync(srvSharepointDws.CreateDwsRequest request)
        {
            return base.Channel.CreateDwsAsync(request);
        }
        
        public System.Threading.Tasks.Task<srvSharepointDws.CreateDwsResponse> CreateDwsAsync(string name, string users, string title, string documents)
        {
            srvSharepointDws.CreateDwsRequest inValue = new srvSharepointDws.CreateDwsRequest();
            inValue.Body = new srvSharepointDws.CreateDwsRequestBody();
            inValue.Body.name = name;
            inValue.Body.users = users;
            inValue.Body.title = title;
            inValue.Body.documents = documents;
            return ((srvSharepointDws.DwsSoap)(this)).CreateDwsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srvSharepointDws.DeleteDwsResponse> srvSharepointDws.DwsSoap.DeleteDwsAsync(srvSharepointDws.DeleteDwsRequest request)
        {
            return base.Channel.DeleteDwsAsync(request);
        }
        
        public System.Threading.Tasks.Task<srvSharepointDws.DeleteDwsResponse> DeleteDwsAsync()
        {
            srvSharepointDws.DeleteDwsRequest inValue = new srvSharepointDws.DeleteDwsRequest();
            inValue.Body = new srvSharepointDws.DeleteDwsRequestBody();
            return ((srvSharepointDws.DwsSoap)(this)).DeleteDwsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srvSharepointDws.GetDwsMetaDataResponse> srvSharepointDws.DwsSoap.GetDwsMetaDataAsync(srvSharepointDws.GetDwsMetaDataRequest request)
        {
            return base.Channel.GetDwsMetaDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<srvSharepointDws.GetDwsMetaDataResponse> GetDwsMetaDataAsync(string document, string id, bool minimal)
        {
            srvSharepointDws.GetDwsMetaDataRequest inValue = new srvSharepointDws.GetDwsMetaDataRequest();
            inValue.Body = new srvSharepointDws.GetDwsMetaDataRequestBody();
            inValue.Body.document = document;
            inValue.Body.id = id;
            inValue.Body.minimal = minimal;
            return ((srvSharepointDws.DwsSoap)(this)).GetDwsMetaDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srvSharepointDws.GetDwsDataResponse> srvSharepointDws.DwsSoap.GetDwsDataAsync(srvSharepointDws.GetDwsDataRequest request)
        {
            return base.Channel.GetDwsDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<srvSharepointDws.GetDwsDataResponse> GetDwsDataAsync(string document, string lastUpdate)
        {
            srvSharepointDws.GetDwsDataRequest inValue = new srvSharepointDws.GetDwsDataRequest();
            inValue.Body = new srvSharepointDws.GetDwsDataRequestBody();
            inValue.Body.document = document;
            inValue.Body.lastUpdate = lastUpdate;
            return ((srvSharepointDws.DwsSoap)(this)).GetDwsDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srvSharepointDws.UpdateDwsDataResponse> srvSharepointDws.DwsSoap.UpdateDwsDataAsync(srvSharepointDws.UpdateDwsDataRequest request)
        {
            return base.Channel.UpdateDwsDataAsync(request);
        }
        
        public System.Threading.Tasks.Task<srvSharepointDws.UpdateDwsDataResponse> UpdateDwsDataAsync(string updates, string meetingInstance)
        {
            srvSharepointDws.UpdateDwsDataRequest inValue = new srvSharepointDws.UpdateDwsDataRequest();
            inValue.Body = new srvSharepointDws.UpdateDwsDataRequestBody();
            inValue.Body.updates = updates;
            inValue.Body.meetingInstance = meetingInstance;
            return ((srvSharepointDws.DwsSoap)(this)).UpdateDwsDataAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srvSharepointDws.RemoveDwsUserResponse> srvSharepointDws.DwsSoap.RemoveDwsUserAsync(srvSharepointDws.RemoveDwsUserRequest request)
        {
            return base.Channel.RemoveDwsUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<srvSharepointDws.RemoveDwsUserResponse> RemoveDwsUserAsync(string id)
        {
            srvSharepointDws.RemoveDwsUserRequest inValue = new srvSharepointDws.RemoveDwsUserRequest();
            inValue.Body = new srvSharepointDws.RemoveDwsUserRequestBody();
            inValue.Body.id = id;
            return ((srvSharepointDws.DwsSoap)(this)).RemoveDwsUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srvSharepointDws.RenameDwsResponse> srvSharepointDws.DwsSoap.RenameDwsAsync(srvSharepointDws.RenameDwsRequest request)
        {
            return base.Channel.RenameDwsAsync(request);
        }
        
        public System.Threading.Tasks.Task<srvSharepointDws.RenameDwsResponse> RenameDwsAsync(string title)
        {
            srvSharepointDws.RenameDwsRequest inValue = new srvSharepointDws.RenameDwsRequest();
            inValue.Body = new srvSharepointDws.RenameDwsRequestBody();
            inValue.Body.title = title;
            return ((srvSharepointDws.DwsSoap)(this)).RenameDwsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srvSharepointDws.FindDwsDocResponse> srvSharepointDws.DwsSoap.FindDwsDocAsync(srvSharepointDws.FindDwsDocRequest request)
        {
            return base.Channel.FindDwsDocAsync(request);
        }
        
        public System.Threading.Tasks.Task<srvSharepointDws.FindDwsDocResponse> FindDwsDocAsync(string id)
        {
            srvSharepointDws.FindDwsDocRequest inValue = new srvSharepointDws.FindDwsDocRequest();
            inValue.Body = new srvSharepointDws.FindDwsDocRequestBody();
            inValue.Body.id = id;
            return ((srvSharepointDws.DwsSoap)(this)).FindDwsDocAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srvSharepointDws.CanCreateDwsUrlResponse> srvSharepointDws.DwsSoap.CanCreateDwsUrlAsync(srvSharepointDws.CanCreateDwsUrlRequest request)
        {
            return base.Channel.CanCreateDwsUrlAsync(request);
        }
        
        public System.Threading.Tasks.Task<srvSharepointDws.CanCreateDwsUrlResponse> CanCreateDwsUrlAsync(string url)
        {
            srvSharepointDws.CanCreateDwsUrlRequest inValue = new srvSharepointDws.CanCreateDwsUrlRequest();
            inValue.Body = new srvSharepointDws.CanCreateDwsUrlRequestBody();
            inValue.Body.url = url;
            return ((srvSharepointDws.DwsSoap)(this)).CanCreateDwsUrlAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srvSharepointDws.CreateFolderResponse> srvSharepointDws.DwsSoap.CreateFolderAsync(srvSharepointDws.CreateFolderRequest request)
        {
            return base.Channel.CreateFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<srvSharepointDws.CreateFolderResponse> CreateFolderAsync(string url)
        {
            srvSharepointDws.CreateFolderRequest inValue = new srvSharepointDws.CreateFolderRequest();
            inValue.Body = new srvSharepointDws.CreateFolderRequestBody();
            inValue.Body.url = url;
            return ((srvSharepointDws.DwsSoap)(this)).CreateFolderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<srvSharepointDws.DeleteFolderResponse> srvSharepointDws.DwsSoap.DeleteFolderAsync(srvSharepointDws.DeleteFolderRequest request)
        {
            return base.Channel.DeleteFolderAsync(request);
        }
        
        public System.Threading.Tasks.Task<srvSharepointDws.DeleteFolderResponse> DeleteFolderAsync(string url)
        {
            srvSharepointDws.DeleteFolderRequest inValue = new srvSharepointDws.DeleteFolderRequest();
            inValue.Body = new srvSharepointDws.DeleteFolderRequestBody();
            inValue.Body.url = url;
            return ((srvSharepointDws.DwsSoap)(this)).DeleteFolderAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DwsSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.DwsSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.DwsSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://puntodereclamo.bancred.com.bo/_vti_bin/Dws.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.DwsSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://puntodereclamo.bancred.com.bo/_vti_bin/Dws.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            DwsSoap,
            
            DwsSoap12,
        }
    }
}
